# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Scott Davis
tagline:             Web Developer
url:                 http://sctdvs.co
paginate:            3
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Scott Davis
  url:               https://twitter.com/sctdvs
  email:             slrd88@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              
